# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
  #     desired widget in your `content/home/` folder.
  #   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Experience
    url: /
    weight: 11
  - name: Volunteer
    url: /
    weight: 12
  - name: Teaching
    url: /
    weight: 13
  - name: Awards
    url: /#news
    weight: 14
  - name: Memberships
    url: /
    weight: 15
  - name: Publications
    url: publication/
    weight: 16
  - name: Projects
    url: /
    weight: 17
  - name: Courses
    url: /
    weight: 18
  # - name: Talks
    # url: /#talks
    # weight: 12
  # - name: Experience
    # url: experience/
    # weight: 20
  # - name: Projects
    # url: projects/
    # weight: 30
  # - name: Teaching
    # url: teaching/
    # weight: 40
